services:
  envoy:
    ports:
      - "8080:8080"
      # The admin shell, maybe also useful in prod at some point
      - "9901:9901"
  frontend:
    # Live access to the code
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
  py-kernel:
    # Live access to the code
    # TODO: this isnt working for some reason?
    # volumes:
    #   - ./kernel/python:/app
    # This is proxied by envoy, so we don't need to expose in production
    ports:
      - "9090:9090"
