services:
  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    image: astraios/envoy
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.${APP_ENV:-prod}
    image: astraios/frontend
    ports:
      - "80:80"
  py-kernel:
    build:
      context: ./kernels/python
      dockerfile: Dockerfile.${APP_ENV:-prod}
    image: astraios/py-kernel
    # This is proxied by envoy, so we don't need to expose in production
    # ports:
    #   - "9090:9090"
