# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.8)
{
  # A helpful description of your flake
  description = "Astraios";

  # Flake inputs
  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*.tar.gz";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/*.tar.gz";
  };

  # Flake outputs that other flakes can use
  outputs = { self, flake-schemas, nixpkgs }:
    let
      # Helpers for producing system-specific outputs
      supportedSystems = [ "x86_64-linux" "aarch64-darwin" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs { inherit system; };
      });
    in {
      # Schemas tell Nix about the structure of your flake's outputs
      schemas = flake-schemas.schemas;

      # Development environments
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          # Pinned packages available in the environment
          packages = with pkgs; [
            nodePackages.pnpm
            nixpkgs-fmt
          ];
        };
      });

      # Production-ready packages
      packages = forEachSupportedSystem ({ pkgs }: rec {
        frontend = pkgs.stdenv.mkDerivation {
          name = "@astraios/frontend";
          src = "${self}/frontend";
          buildInputs = with pkgs; [ nodePackages.pnpm ];
          buildPhase = ''
            export HOME=$TEMPDIR
            pnpm config set strict-ssl false
            pnpm install
            pnpm run build
          '';
          installPhase = ''
            mkdir -p $out
            cp -r dist/* $out/
          '';
        };
        default = frontend;
        envoyImage = pkgs.dockerTools.buildImage {
          name = "@astraios/envoyproxy";
          tag = "latest";
          contents = [ frontend.packages.x86_64-linux.default ];
          config = {
            Cmd = [ "-c /etc/envoy/envoy.yaml" "-l trace" "--log-path /tmp/envoy_info.log" ];
            Entrypoint = [ "/usr/local/bin/envoy" ];
            # ExposedPorts = { "80/tcp" = {}; };
            # Volumes = { "/etc/envoy" = {}; };
          };
        };
      });
    };
}
