# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Install git and protoc
RUN apt-get update && \
    apt-get install -y git protobuf-compiler && \
    rm -rf /var/lib/apt/lists/*

# Install dependencies.
COPY . /app
RUN pip install -e .

CMD ["python", "-m", "astraios_py"]
