# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Install git and protoc
RUN apt-get update && \
    apt-get install -y git protobuf-compiler && \
    rm -rf /var/lib/apt/lists/*

# Preinstall dependencies.
COPY . /app
# COPY requirements-dev.lock ./
RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -r requirements.lock
RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -r requirements-dev.lock
RUN apt-get update && apt-get install -y graphviz

# RUN pip install -e .

# TODO: make this work
# CMD ["watchmedo", "auto-restart", "--recursive", "--pattern=\"*.py\"", "--directory=\"/app/src/astraios_py\"", "python", "--", "-m", "src/astraios_py/__main__.py"]

CMD ["python", "-m", "astraios_py"]
